# Generated by Django 3.2.6 on 2022-04-02 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=2048)),
                ('posted_by', models.CharField(default='root', max_length=50)),
                ('posted_at', models.DateTimeField(default=datetime.datetime(2022, 4, 2, 1, 24, 52, 215363, tzinfo=utc))),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
